### ISSUE TITLE
Pass command line options to typst

### ISSUE THREAD

**Issue by ntrocado** [jmpunkt/ox-typst#13]
As far as I know it's not currently possible to pass arguments (e.g. `--root`) to the typst executable. This can be accomplished with a simple bash script but I think it would be preferable to have the possibility inside emacs - for example with a mechanism analogous to `org-latex-pdf-process`. If you agree I'd be happy to try my hand at it and submit a PR.

**Comment by jmpunkt** [comment]
That sounds like something we need. I guess the LaTeX way is the better way. By allowing the user to specify a format-string. Since we only provide the file, it should be straight forward. Compared to LaTeX we do **not** have to insert/replace different kind of strings (compiler, bibtex, etc.) into the command line.

I guess something like this would be powerful enough to cover most scenarios.
```elisp
(defcustom org-typst-process
   "..."
"typst c %s")
```
This would replace `org-typst-bin`, since it is not needed anymore.
